export { detectShells, defaultCwd } from './pty/shellDetector'
export { SessionManager } from './connection/SessionManager'
export type { SshSessionOptions } from './connection/SshSession'
export type { HostKeyInfo, HostKeyVerifier, TerminalSession } from './connection/types'
export { establishChain, agentPath, friendlySshError } from './connection/establish'
export type { ChainEndpoint, EstablishedChain } from './connection/establish'
export { TunnelService } from './connection/TunnelService'
export type { TunnelConnectionConfig } from './connection/TunnelService'
export { SftpService } from './sftp/SftpService'
export { deriveSshArgsFromLoginSteps } from './sftp/sftpOverExec'
export { listSerialPorts } from './connection/SerialSession'
export { BulkService } from './bulk/BulkService'
export type { BulkTarget, BulkResult } from './bulk/BulkService'
export { ping, dnsLookup, checkPort, scanCommonPorts } from './nettools/netTools'
export type { PingResult, DnsResult, PortScanEntry } from './nettools/netTools'
export { MonitorService } from './monitor/MonitorService'
export type { MetricSample, MonitorTarget } from './monitor/MonitorService'
export { AiService } from './ai/AiService'
export type { AiProvider, AiRuntimeConfig, AiAskRequest, AiAskResult, AiMode } from './ai/AiService'
export { resolveSecret, detectSecretProvider } from './secrets/SecretsService'
export type { SecretProvider } from './secrets/SecretsService'
export { importSshConfig, parseSshConfig } from './importers/sshConfig'
export { VaultService } from './vault/VaultService'
export type { KnownHostRecord, ResolvedConnection, ResolvedEndpoint, SyncSnapshot } from './vault/VaultService'
export { deriveSyncKey, newSyncSalt } from './vault/crypto'
export { SyncService, createBackend } from './sync/SyncService'
export type { SyncBackend, SyncResult } from './sync/SyncService'
